[pytest]
asyncio_mode = strict
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = tests/unit tests/integration
filterwarnings =
    ignore::DeprecationWarning
